name: f1n
description: f1news

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: 3.0.8
  html: ^0.14.0+3
  xml: ^3.6.1
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+1
  provider: ^4.2.0
  animations: ^1.1.1
  sa_stateless_animation: ^1.0.1
  cached_network_image: ^2.2.0+1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.2
  mobx_codegen: ^1.1.0+1


flutter:
  uses-material-design: true

