name:  Test, build and deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.3.2
        with:
          flutter-version: '1.17.3'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test